---
  AWSTemplateFormatVersion: "2010-09-09"
  Description: "Create an EC2 Instance and Security Group"

  Parameters:
    KeyName:
      Description: "Existing Key Pair Name"
      Type: AWS::EC2::KeyPair::KeyName
      ConstraintDescription: "Must be the name of an existing Key Pair"
    InstanceType:
      Description: "Instance Type"
      Type: String
      Default: "t3.small"
      AllowedValues: [t2.nano, t2.micro, t3.small, t3.medium]
    LatestAmiId:
      Type: AWS::EC2::Image::Id
      Default: "ami-047bb4163c506cd98"

  Resources:
    InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: "Enable SSH Access"
        GroupName: "CFN SSH"
        VpcId: "vpc-0fb7fa6c01ca01f82"
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"

    LaunchConfiguration:
      Type: AWS::AutoScaling::LaunchConfiguration
      Properties:
        InstanceType:
          Ref: "InstanceType"
        SecurityGroups:
          - 
            Ref: "InstanceSecurityGroup"
        KeyName:
          Ref: "KeyName"
        ImageId:
          Ref: "LatestAmiId"

    AutoScalingGroup:
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties:
        LaunchConfigurationName:
          Ref: LaunchConfiguration
        MinSize: '8'
        MaxSize: '8'
        VPCZoneIdentifier: ["subnet-0ddd5c04486825854", "subnet-03c1e81a45ba28028"]
